import { buscarJogos } from '@/services/jogos'
import { AppShell } from '@/components/AppShell'
import type { Jogo } from '@/types/jogo'

export const revalidate = 0 // sempre busca dados frescos

const JOGOS_PLACEHOLDER: Jogo[] = [
  {
    id: '1',
    nome_do_jogo: 'Spider-Man: Miles Morales',
    plataforma: 'STEAM',
    genero: 'Ação e Aventura',
    status: 'Zerei',
    valor_pago: 60.98,
    data_inicio: '2025-12-23',
    nota_pessoal: 10,
    data_finalizada: '2026-01-01',
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Spider-Man_Miles_Morales.jpeg',
  },
  {
    id: '2',
    nome_do_jogo: 'Esquadrão Suicida: Mate a Liga da Justiça',
    plataforma: 'STEAM',
    genero: 'RPG de Ação e Tiro',
    status: 'Desisti',
    valor_pago: 13.99,
    data_inicio: '2026-02-11',
    nota_pessoal: 5,
    data_finalizada: '2026-02-14',
    desistiu: true,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/5/57/Suicide_Squad_Kill_the_Justice_League_cover_art.jpg',
  },
  {
    id: '3',
    nome_do_jogo: 'Tomb Raider The Of Rise',
    plataforma: 'STEAM',
    genero: 'Ação e Aventura de Sobrevivencia',
    status: 'Pausa',
    valor_pago: 13,
    data_inicio: '2026-01-20',
    nota_pessoal: null,
    data_finalizada: null,
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Rise_of_the_Tomb_Raider_cover.jpg',
  },
  {
    id: '4',
    nome_do_jogo: 'Red Dead Redemption 2',
    plataforma: 'STEAM TOOLS',
    genero: 'Aventura',
    status: 'Querendo...',
    valor_pago: null,
    data_inicio: null,
    nota_pessoal: null,
    data_finalizada: '2023-11-05',
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
  },
  {
    id: '5',
    nome_do_jogo: 'Lords Of The Fallen',
    plataforma: 'STEAM',
    genero: 'Soulslike, RPG Ação',
    status: 'Querendo...',
    valor_pago: 10,
    data_inicio: null,
    nota_pessoal: null,
    data_finalizada: null,
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/5/5f/Lords_of_the_Fallen_2023_cover.jpg',
  },
  {
    id: '6',
    nome_do_jogo: 'Spider-Man Remastered',
    plataforma: 'HYDRA',
    genero: 'Ação e Aventura',
    status: 'Zerei',
    valor_pago: 0,
    data_inicio: '2026-01-18',
    nota_pessoal: 10,
    data_finalizada: '2026-02-10',
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Spider-Man_PS4_cover.jpg',
  },
  {
    id: '7',
    nome_do_jogo: 'God of War: Ragnarök',
    plataforma: 'STEAM TOOLS',
    genero: 'Ação',
    status: 'Querendo...',
    valor_pago: null,
    data_inicio: null,
    nota_pessoal: null,
    data_finalizada: null,
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
  },
  {
    id: '8',
    nome_do_jogo: 'Spider-Man 2',
    plataforma: 'STEAM TOOLS',
    genero: 'Ação e Aventura',
    status: 'Querendo...',
    valor_pago: null,
    data_inicio: null,
    nota_pessoal: null,
    data_finalizada: null,
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/3/32/Marvel%27s_Spider-Man_2_cover_art.jpg',
  },
  {
    id: '9',
    nome_do_jogo: 'The Last of Us 1 Remake',
    plataforma: 'STEAM TOOLS',
    genero: 'Ação e Aventura',
    status: 'Zerei',
    valor_pago: 0,
    data_inicio: '2026-02-13',
    nota_pessoal: 10,
    data_finalizada: '2026-02-19',
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/4/46/The_Last_of_Us_%E2%80%93_Part_I_Cover.jpg',
  },
  {
    id: '10',
    nome_do_jogo: 'Gears of War: Ultimate Edition',
    plataforma: 'GAME PASS',
    genero: 'Ação e Aventura',
    status: 'Desisti',
    valor_pago: 0,
    data_inicio: '2026-02-20',
    nota_pessoal: null,
    data_finalizada: '2026-02-20',
    desistiu: true,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/8/8f/Gears_of_War_Ultimate_Edition_cover.jpg',
  },
  {
    id: '11',
    nome_do_jogo: 'God of War: 2018',
    plataforma: 'HYDRA',
    genero: 'Ação e Aventura',
    status: 'Zerei',
    valor_pago: 0,
    data_inicio: '2026-01-10',
    nota_pessoal: 10,
    data_finalizada: '2026-01-18',
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg',
  },
  {
    id: '12',
    nome_do_jogo: 'Katana Zero',
    plataforma: 'STEAM TOOLS',
    genero: 'Ação, Indie',
    status: 'Jogando',
    valor_pago: 0,
    data_inicio: '2026-02-28',
    nota_pessoal: null,
    data_finalizada: null,
    desistiu: false,
    capa_url: 'https://upload.wikimedia.org/wikipedia/en/1/17/Katana_Zero_cover_art.jpg',
  },
]

export default async function HomePage() {
  let jogos: Jogo[] = []

  try {
    jogos = await buscarJogos()
  } catch {
    // Se o Supabase ainda não estiver configurado, usa placeholders
    jogos = JOGOS_PLACEHOLDER
  }

  return <AppShell jogosList={jogos} />
}
